#!/bin/bash
set -u -e -C

# Legit use:
#
#     $ mkdir foo
#     $ ./unqoted3
#
# Illegit use:
#
#     $ mkdir 'x -o x'        # directory classified as file
#     $ touch 'x -o -v a[0$(date>&2)]'      # code execution
#
#     $ ./unqoted3

for file in *; do

    if [ -f $file ]; then
        echo "Is a file: ${file}"
    else
        echo "Not a file: ${file}"
    fi

done

# [1]: https://unix.stackexchange.com/questions/171346/security-implications-of-forgetting-to-quote-a-variable-in-bash-posix-shells
