#!/bin/bash
set -u -e -C
shopt -s failglob

# Arbitrary code execution, taken from [1].
#
# Legit use:
#
#     $ ./unqoted2 LALA
#
# Illegit use:
#
#     $ ./unqoted2 'x BEGIN{system("date")}'

cat <<. | awk -v awkVar=$1 '{ $2 = awkVar; print }' -
There once was a man from Nantucket
Who kept all his cash in a bucket.
.

# [1]: https://unix.stackexchange.com/questions/171346/security-implications-of-forgetting-to-quote-a-variable-in-bash-posix-shells
