#!/bin/bash
set -u -e -C

# Arbitrary code execution, taken from [1].
#
#     $ mkdir foo             # works
#     $ mkdir 'x -o x'        # directory classified as file
#     $ touch 'x -o -v a[0$(date>&2)]'      # code execution

for file in *; do

    if test -f $file; then          # here is the bug!

        echo "Is file: ${file}"
    else
        echo "No file: ${file}"
    fi

done

# [1]: https://unix.stackexchange.com/questions/171346/security-implications-of-forgetting-to-quote-a-variable-in-bash-posix-shells
